; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "AMT EgoGIG"
#define ConverterName "WAV converter(LEGACY)"
#define MyAppNameUn "Uninstall AMT EgoGIG"

;#define MyAppVersionREPLACE
#define MyAppVersion "1.1.3.0"
#define MyAppPublisher "AMT Electronics"
#define MyAppURL "http://www.amtelectronics.ru/"
#define MyAppExeName "EgoGIG.exe"
#define ConverterAppExeName "WavConverter.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{19986140-514D-47F1-8941-FD32043F9083}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf64}\{#MyAppName}
DefaultGroupName={#MyAppPublisher}
;DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=EgoGIG_Setup
SetupIconFile=.\resources\spirit.ico
Compression=lzma
SolidCompression=yes
DisableDirPage=no

WizardSmallImageFile=.\resources\logo.bmp
UninstallDisplayIcon={app}\{#MyAppExeName}
;WizardImageFile=image.bmp

[Languages]
Name: english; MessagesFile: compiler:Default.isl
Name: russian; MessagesFile: compiler:Languages\Russian.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: release\*; DestDir: {app}; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "release\vc_redist.x64.exe"; DestDir: {tmp}; Flags: deleteafterinstall

[Icons]
Name: {commondesktop}\{#MyAppName}; Filename: {app}\{#MyAppExeName}; Tasks: desktopicon
Name: {group}\{#MyAppName}; Filename: {app}\{#MyAppExeName}
Name: {group}\{#ConverterName}; Filename: {app}\{#ConverterAppExeName}
Name: {group}\{cm:ProgramOnTheWeb,{#MyAppName}}; Filename: {#MyAppURL}
Name: {group}\{cm:UninstallProgram,{#MyAppName}}; Filename: {uninstallexe}
Name: {group}\{#MyAppNameUn}; Filename: "{app}\unins000.exe";


[Run]
Filename: {tmp}\vc_redist.x64.exe; \
    Parameters: "/q /passive /Q:a /c:""msiexec /q /i vcredist.msi"""; \
    StatusMsg: "Installing VC++ 2019 Redistributables..."

Filename: {app}\{#MyAppExeName}; Description: {cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}; Flags: nowait postinstall skipifsilent

